services:
  bank_rest:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank_db
      - POSTGRES_USER=kekich
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local