#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

#spring:
#  liquibase:
#    enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bank_db
#    username: kekich
#    password: 12345
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto:
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: kekich
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

bank_rest-main:
  app:
    secret: 2d5c19105c36aa0523beaefe1387b0d586a59bbff3d3436791221071ab6e6dbe
    expirationMs: 7200000


server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs


