#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

#spring:
#  liquibase:
#    enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bank_db
#    username: kekich
#    password: 12345
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto:
spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: kekich
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs