{
  "openapi": "3.1.0",
  "info": {
    "version": "1",
    "title": "Bank Cards API",
    "contact": {
      "name": "kekich"
    }
  },

  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/user/send-money": {
      "post": {
        "tags": [
          "user-controller"
        ],
        "operationId": "sendMoney",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SendMoneyDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/auth/signUp": {
      "post": {
        "tags": [
          "security-controller"
        ],
        "operationId": "signUp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUp"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/signIn": {
      "post": {
        "tags": [
          "security-controller"
        ],
        "operationId": "signIn",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignIn"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/card/create": {
      "post": {
        "tags": [
          "card-controller"
        ],
        "operationId": "createCard",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/admin/manage/card/delete": {
      "post": {
        "tags": [
          "admin-controller"
        ],
        "operationId": "manageCardDelete",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteCardDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/user/get/cards/hide": {
      "get": {
        "tags": [
          "user-controller"
        ],
        "operationId": "getUserCards",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CardResponseDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/get/cards/full": {
      "get": {
        "tags": [
          "user-controller"
        ],
        "operationId": "getUserCardFull",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Card"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/admin/get/all/users": {
      "get": {
        "tags": [
          "admin-controller"
        ],
        "operationId": "getAllUsers",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/UserViewDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/admin/get/all/cards": {
      "get": {
        "tags": [
          "admin-controller"
        ],
        "operationId": "getAllCards",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Card"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SendMoneyDto": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int32"
          },
          "cardNumberFrom": {
            "type": "string"
          },
          "cardNumberTo": {
            "type": "string"
          }
        }
      },
      "SignUp": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "SignIn": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "DeleteCardDto": {
        "type": "object",
        "properties": {
          "cardNumber": {
            "type": "string"
          }
        }
      },
      "CardResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "cardNumber": {
            "type": "string"
          },
          "owner": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "balance": {
            "type": "integer",
            "format": "int32"
          },
          "dateAdd": {
            "type": "string",
            "format": "date"
          },
          "dateExpire": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "Card": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "cardNumber": {
            "type": "string"
          },
          "owner": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "balance": {
            "type": "integer",
            "format": "int32"
          },
          "dateAdd": {
            "type": "string",
            "format": "date"
          },
          "dateExpire": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "UserViewDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "roleId": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
}